#############################################################################
# Makefile for building: Flock
# Generated by qmake (2.01a) (Qt 4.7.0) on: Wed Mar 21 14:22:56 2012
# Project:  Flock.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Flock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSING_QT_CREATOR -DNGL_DEBUG -DLINUX -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/local -Iinclude -I+=ui -I../NGL/include -I/usr/X11R6/include -Imoc -Iui
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -L/usr/local/lib -L/$(HOME)/NGL/lib -l NGL -lGLEW -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Boid.cpp \
		src/BoidManager.cpp \
		src/Predator.cpp \
		src/Scene.cpp \
		src/Lattice.cpp \
		src/Export.cpp moc/moc_MainWindow.cpp \
		moc/moc_GLWindow.cpp
OBJECTS       = obj/main.o \
		obj/MainWindow.o \
		obj/GLWindow.o \
		obj/Boid.o \
		obj/BoidManager.o \
		obj/Predator.o \
		obj/Scene.o \
		obj/Lattice.o \
		obj/Export.o \
		obj/moc_MainWindow.o \
		obj/moc_GLWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Flock.pro
QMAKE_TARGET  = Flock
DESTDIR       = 
TARGET        = Flock

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Flock.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Flock.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile Flock.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Flock1.0.0 || $(MKDIR) obj/Flock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Flock1.0.0/ && $(COPY_FILE) --parents include/MainWindow.h include/GLWindow.h include/Boid.h include/BoidManager.h include/Predator.h include/Scene.h include/Lattice.h include/Export.h obj/Flock1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/GLWindow.cpp src/Boid.cpp src/BoidManager.cpp src/Predator.cpp src/Scene.cpp src/Lattice.cpp src/Export.cpp obj/Flock1.0.0/ && $(COPY_FILE) --parents ui/MainWindow.ui obj/Flock1.0.0/ && (cd `dirname obj/Flock1.0.0` && $(TAR) Flock1.0.0.tar Flock1.0.0 && $(COMPRESS) Flock1.0.0.tar) && $(MOVE) `dirname obj/Flock1.0.0`/Flock1.0.0.tar.gz . && $(DEL_FILE) -r obj/Flock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
moc/moc_MainWindow.cpp: include/GLWindow.h \
		include/BoidManager.h \
		include/Boid.h \
		include/Predator.h \
		include/Scene.h \
		include/Lattice.h \
		include/Export.h \
		include/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_GLWindow.cpp: include/BoidManager.h \
		include/Boid.h \
		include/Predator.h \
		include/Scene.h \
		include/Lattice.h \
		include/Export.h \
		include/GLWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/GLWindow.h -o moc/moc_GLWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_MainWindow.h
ui/ui_MainWindow.h: ui/MainWindow.ui
	/usr/bin/uic-qt4 ui/MainWindow.ui -o ui/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/BoidManager.h \
		include/Boid.h \
		include/Predator.h \
		include/Scene.h \
		include/Lattice.h \
		include/Export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/BoidManager.h \
		include/Boid.h \
		include/Predator.h \
		include/Scene.h \
		include/Lattice.h \
		include/Export.h \
		ui/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/GLWindow.o: src/GLWindow.cpp include/GLWindow.h \
		include/BoidManager.h \
		include/Boid.h \
		include/Predator.h \
		include/Scene.h \
		include/Lattice.h \
		include/Export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLWindow.o src/GLWindow.cpp

obj/Boid.o: src/Boid.cpp include/Boid.h \
		include/BoidManager.h \
		include/Predator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Boid.o src/Boid.cpp

obj/BoidManager.o: src/BoidManager.cpp include/BoidManager.h \
		include/Boid.h \
		include/Predator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/BoidManager.o src/BoidManager.cpp

obj/Predator.o: src/Predator.cpp include/Predator.h \
		include/Boid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Predator.o src/Predator.cpp

obj/Scene.o: src/Scene.cpp include/Scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Scene.o src/Scene.cpp

obj/Lattice.o: src/Lattice.cpp include/Lattice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Lattice.o src/Lattice.cpp

obj/Export.o: src/Export.cpp include/Export.h \
		include/BoidManager.h \
		include/Boid.h \
		include/Predator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Export.o src/Export.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_GLWindow.o: moc/moc_GLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_GLWindow.o moc/moc_GLWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

